<%@page session="false" contentType="text/html" pageEncoding="utf-8"%>

<jsp:include page="/header.jsp" />

<!--====== App Content ======-->
    <div class="app-content">

        <!--====== Section 1 ======-->
        <div class="u-s-p-y-60">

            <!--====== Section Content ======-->
            <div class="section__content">
                <div class="container">
                    <div class="breadcrumb">
                        <div class="breadcrumb__wrap">
                            <ul class="breadcrumb__list">
                                <li class="has-separator">

                                    <a href="index.html">Home</a></li>
                                <li class="is-marked">

                                    <a href="signup.html">Signup</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--====== End - Section 1 ======-->


        <!--====== Section 2 ======-->
        <div class="u-s-p-b-60">

            <!--====== Section Intro ======-->
            <div class="section__intro u-s-m-b-60">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="section__text-wrap">
                                <h1 class="section__heading u-c-secondary">CREATE AN ACCOUNT</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--====== End - Section Intro ======-->


            <!--====== Section Content ======-->
            <div class="section__content">
                <div class="container">
                    <div class="row row--center">
                        <div class="col-lg-6 col-md-8 u-s-m-b-30">
                            <div class="l-f-o">
                                <div class="l-f-o__pad-box">
                                    <h1 class="gl-h1">PERSONAL INFORMATION</h1>
                                    <form class="l-f-o__form" id="signup-form">
                                        <div class="gl-s-api">
                                            <div class="u-s-m-b-15">

                                                <button class="gl-s-api__btn gl-s-api__btn--fb" type="button"><i
                                                        class="fab fa-facebook-f"></i>

                                                    <span>Signup with Facebook</span></button>
                                            </div>
                                            <div class="u-s-m-b-30">

                                                <button class="gl-s-api__btn gl-s-api__btn--gplus" type="button"><i
                                                        class="fab fa-google"></i>

                                                    <span>Signup with Google</span></button>
                                            </div>
                                        </div>
                                        <div class="u-s-m-b-30">

                                            <label class="gl-label" for="reg-fname">FIRST NAME *</label>

                                            <input class="input-text input-text--primary-style" type="text"
                                                   id="reg-fname" placeholder="First Name"></div>
                                        <div class="u-s-m-b-30">

                                            <label class="gl-label" for="reg-lname">LAST NAME *</label>

                                            <input class="input-text input-text--primary-style" type="text"
                                                   id="reg-lname" placeholder="Last Name"></div>
                                        <div class="gl-inline">
                                            <div class="u-s-m-b-30">

                                                <!--====== Date of Birth Select-Box ======-->

                                                <span class="gl-label">BIRTHDAY</span>
                                                <div class="gl-dob">
                                                    <select class="select-box select-box--primary-style" id="month">
                                                        <option selected>Month</option>
                                                        <!-- Month options will be generated by JavaScript -->
                                                    </select>
                                                    <select class="select-box select-box--primary-style" id="day">
                                                        <option selected>Day</option>
                                                        <!-- Day options will be generated by JavaScript -->
                                                    </select>
                                                    <select class="select-box select-box--primary-style" id="year">
                                                        <option selected>Year</option>
                                                        <!-- Year options will be generated by JavaScript -->
                                                    </select>
                                                </div>
                                                <!--====== End - Date of Birth Select-Box ======-->
                                            </div>
                                            <div class="u-s-m-b-30">
                                                <label class="gl-label" for="gender">GENDER</label>
                                                <select class="select-box select-box--primary-style u-w-100"
                                                        id="gender">
                                                    <option selected>Select</option>
                                                    <option value="male">Male</option>
                                                    <option value="female">Female</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="u-s-m-b-30">

                                            <label class="gl-label" for="reg-email">E-MAIL *</label>

                                            <input class="input-text input-text--primary-style" type="text"
                                                   id="reg-email" placeholder="Enter E-mail"></div>
                                        <span id="password-error" class="section__span u-c-brand"></span>
                                        <div class="u-s-m-b-30">

                                            <label class="gl-label" for="reg-password">PASSWORD *</label>

                                            <input class="input-text input-text--primary-style" type="password"
                                                   id="reg-password" placeholder="Enter Password">
                                        </div>
                                        <div class="u-s-m-b-30">
                                            <label class="gl-label" for="reg-confirm-password">CONFIRM PASSWORD
                                                *</label>
                                            <input class="input-text input-text--primary-style" type="password"
                                                   id="reg-confirm-password" placeholder="Confirm Password">
                                        </div>

                                        <div class="u-s-m-b-30">
                                            <label class="gl-label" for="reg-job">JOB *</label>
                                            <input class="input-text input-text--primary-style" type="text" id="reg-job"
                                                   placeholder="Enter Job">
                                        </div>

                                        <div class="u-s-m-b-30">
                                            <label class="gl-label" for="reg-interests">INTERESTS *</label>
                                            <input class="input-text input-text--primary-style" type="text"
                                                   id="reg-interests" placeholder="Enter Interests">
                                        </div>

                                        <div class="u-s-m-b-30">
                                            <label class="gl-label" for="reg-credit-limit">CREDIT LIMIT *</label>
                                            <input class="input-text input-text--primary-style" type="number"
                                                   id="reg-credit-limit" placeholder="Enter Credit Limit">
                                        </div>


                                        <div class="u-s-m-b-15">

                                            <button class="btn btn--e-transparent-brand-b-2" type="submit">CREATE
                                            </button>
                                        </div>

                                        <a class="gl-link" href="#">Return to Store</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--====== End - Section Content ======-->
        </div>
        <!--====== End - Section 2 ======-->
    </div>
    <!--====== End - App Content ======-->

<jsp:include page="/footer.jsp" />

</div>
    <!--====== End - Main App ======-->

<!--====== Google Analytics: change UA-XXXXX-Y to be your site's ID ======-->
<script>
    window.ga = function () {
        ga.q.push(arguments)
    };
    ga.q = [];
    ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto');
    ga('send', 'pageview')
</script>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>

<!--====== Vendor Js ======-->
<script src="js/vendor.js"></script>

<!--====== jQuery Shopnav plugin ======-->
<script src="js/jquery.shopnav.js"></script>

<!--====== App ======-->
<script src="js/app.js"></script>

<!--====== Imports ======-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

<!--====== Custom Js ======-->
<script src="js/signup.js"></script>
<!--<script src="js/date-generator.js"></script>-->

<!--====== Noscript ======-->
<noscript>
    <div class="app-setting">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="app-setting__wrap">
                        <h1 class="app-setting__h1">JavaScript is disabled in your browser.</h1>

                        <span class="app-setting__text">Please enable JavaScript in your browser or upgrade to a JavaScript-capable browser.</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</noscript>
</body>
</html>